general:
  working_directory:
  output: intetn_nl_stats.sqlite
  cache_directory: cache
  sheet_renames:
    statline:
      pattern: "statline_"
      replace: ""
statistics:
  internet_gk_vanaf_2: # bedrijfsgrootte, per gk vanaf 2
    do_it: true
    groupby:
      gk: gk_vanaf_2
  statline_gk_all: # bedrijfsgrootte,  2 en meer WP
    do_it: true
    groupby:
      gk: gk_all_wp
  statline_sbi_digit1:
    do_it: false
    groupby:
      sbi: sbi_digit1_statline
index:
  be_id: be_id
weight: ratio_units
translations:
  yes_no:
    'yes': 1  # the strings yes en no worden naar bools vertaald. Zet '' om als string te houden
    'no': 0
  passed_failed:
    passed: 1
    failed: 0
  good_bad:
    good: 1
    bad: 0
  ok_info:
    ok: 1
    info: 0
variables:
  score:
    percentage:
      type: percentage
      label: "Score"
  results:
    categories_web_ipv6_verdict:
      type: bool
      label: "Ipv6"
    categories_web_dnssec_verdict:
      type: bool
      label: "dnssec"
    tests_web_ipv6_ws_reach_status:
      type: bool
      label: "Ipv6 Ws Reach status"
      description: "What is the status of Ipv6 reached"
    tests_web_https_tls_cipherorder_verdict:
      type: dict
      translate:
        bad: 1
        good: 2
        not-tested: 3
        warning: 4
        seclevel-bad: 5
      options:
        1: Bad
        2: Good
        3: Not tested
        4: Warning
        5: Security level bad
      label: Web Https Cipher order verdict
module_info:
  score:
    include: true
    label: Totaal score
    description: Totale score van alle resultaten
  results:
    include: true
    label: Scan resutls
    description: Micro variabeles scan result
gk_data:
    gk3_label:
      GK002_010:  0
      GK010_050: 40
      GK050_250: 60
      GK250_: 82
