general:
  working_directory:
statistics:
  internet_gk_vanaf_2: # bedrijfsgrootte, per gk vanaf 2
    do_it: true
    groupby:
      gk: gk_vanaf_2
index:
  be_id: be_id
weight: ratio_units
variables:
  percentage:
    type: percentage
    label: "Score"
  category_web_ipv6_verdict:
    label: "Ipv6"
  category_web_dnssec_verdict:
    label: "dnssec"
gk_data:
    gk3_label:
      GK002_010:  0
      GK010_050: 40
      GK050_250: 60
      GK250_: 82
